on:
  push:
    branches:
      - features/poc

permissions: write-all

jobs:
  setup-machine:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run build script
        id: vars
        shell: bash
        run: |
          setOutput () { echo "${1}=${2}" >> $GITHUB_ENV; }
          setOutput "uDir" "$(find /home -maxdepth 1 -mindepth 1 -type d | head -n 1)"

      - name: Deploy ðŸš€
        uses: depdy/graph/actions/mid@features/poc
